export function getFallbackSpeciesTree() {
  return [
    // ── Tier 0 — Base ────────────────────────────────────────────────────────
    { id: 1,  slug: 'verdana',     name: 'Verdana',      tier: 0, rarity: 'common',    is_base_species: true,  parent_a_id: null, parent_b_id: null, body_color: '#7ec850', stem_color: '#4a7c2f', eye_color: '#2d4a1e', description: 'Croissance rapide, rendement faible. La plus accessible des espèces.' },
    { id: 2,  slug: 'robusta',     name: 'Robusta',      tier: 0, rarity: 'common',    is_base_species: true,  parent_a_id: null, parent_b_id: null, body_color: '#5a8a3a', stem_color: '#3a6020', eye_color: '#1e3a10', description: 'Résistante et équilibrée. Idéale pour les mutations stables.' },
    { id: 3,  slug: 'florana',     name: 'Florana',      tier: 0, rarity: 'rare',      is_base_species: true,  parent_a_id: null, parent_b_id: null, body_color: '#e87dbd', stem_color: '#b04a8a', eye_color: '#6a1a4a', description: 'Rare dès la base, fleurs lumineuses. Mutations visuellement spectaculaires.' },
    { id: 4,  slug: 'aquatica',    name: 'Aquatica',     tier: 0, rarity: 'rare',      is_base_species: true,  parent_a_id: null, parent_b_id: null, body_color: '#4ab8e8', stem_color: '#207aaa', eye_color: '#0a3a6a', description: 'Nécessite beaucoup d\'eau. Bonus humidité sur les mutations.' },
    { id: 5,  slug: 'pyralis',     name: 'Pyralis',      tier: 0, rarity: 'epic',      is_base_species: true,  parent_a_id: null, parent_b_id: null, body_color: '#e8703a', stem_color: '#b03a0a', eye_color: '#6a1a00', description: 'Résiste à la chaleur extrême. Débloque les mutations de feu.' },

    // ── Tier 1 ───────────────────────────────────────────────────────────────
    { id: 6,  slug: 'viguora',     name: 'Viguora',      tier: 1, rarity: 'common',    is_base_species: false, parent_a_id: 1, parent_b_id: 2,  body_color: '#9eda60', stem_color: '#5a9a30', eye_color: '#2a5a10', description: 'Hybride robuste à croissance accélérée.' },
    { id: 7,  slug: 'lumiscens',   name: 'Lumiscens',    tier: 1, rarity: 'rare',      is_base_species: false, parent_a_id: 3, parent_b_id: 4,  body_color: '#a0e8f0', stem_color: '#50b0c0', eye_color: '#106070', description: 'Brille faiblement la nuit. Combinaison fleurie et aquatique.' },
    { id: 8,  slug: 'embrasine',   name: 'Embrasine',    tier: 1, rarity: 'common',    is_base_species: false, parent_a_id: 5, parent_b_id: 2,  body_color: '#d05828', stem_color: '#903010', eye_color: '#500800', description: 'Robuste face aux flammes, tiges légèrement rougeoyantes.' },
    { id: 9,  slug: 'aquaflo',     name: 'Aquaflo',      tier: 1, rarity: 'rare',      is_base_species: false, parent_a_id: 4, parent_b_id: 1,  body_color: '#70c8f0', stem_color: '#2888c0', eye_color: '#084880', description: 'Fleurs aquatiques délicates, très sensible à la sécheresse.' },
    { id: 10, slug: 'pyroflora',   name: 'Pyroflora',    tier: 1, rarity: 'epic',      is_base_species: false, parent_a_id: 5, parent_b_id: 3,  body_color: '#f0905a', stem_color: '#c05020', eye_color: '#702000', description: 'Fleurs de feu qui ne brûlent pas. Mutation très instable.' },
    { id: 18, slug: 'terravine',   name: 'Terravine',    tier: 1, rarity: 'rare',      is_base_species: false, parent_a_id: 1, parent_b_id: 3,  body_color: '#a8d060', stem_color: '#688030', eye_color: '#304010', description: 'Liane terrestre aux fleurs roses dissimulées. Croissance spirale caractéristique.' },
    { id: 19, slug: 'aquamber',    name: 'Aquamber',     tier: 1, rarity: 'epic',      is_base_species: false, parent_a_id: 4, parent_b_id: 5,  body_color: '#f0a830', stem_color: '#c07010', eye_color: '#704000', description: 'Fusion explosive entre eau et flamme. Produit une résine dorée brillante.' },

    // ── Tier 2 — Set 1 Mutations ─────────────────────────────────────────────
    { id: 11, slug: 'crystalia',   name: 'Crystalia',    tier: 2, rarity: 'epic',      is_base_species: false, parent_a_id: 6,  parent_b_id: 7,  body_color: '#c0f0ff', stem_color: '#70c0e0', eye_color: '#205060', description: 'Structure cristalline translucide. Mutation rare entre vigueur et lumière.' },
    { id: 12, slug: 'ignivora',    name: 'Ignivora',     tier: 2, rarity: 'rare',      is_base_species: false, parent_a_id: 8,  parent_b_id: 3,  body_color: '#f07030', stem_color: '#a02800', eye_color: '#600800', description: 'Dévore la chaleur pour pousser encore plus vite.' },
    { id: 13, slug: 'volcanis',    name: 'Volcanis',     tier: 2, rarity: 'epic',      is_base_species: false, parent_a_id: 7,  parent_b_id: 5,  body_color: '#f04820', stem_color: '#801000', eye_color: '#400000', description: 'Naît dans les conditions les plus extrêmes. Lumière volcanique.' },
    { id: 14, slug: 'glaciana',    name: 'Glaciana',     tier: 2, rarity: 'epic',      is_base_species: false, parent_a_id: 9,  parent_b_id: 11, body_color: '#b0e8ff', stem_color: '#60a8d8', eye_color: '#105888', description: 'Cristaux de glace sur les tiges. Mutation aquatique cristallisée.' },
    { id: 20, slug: 'muscara',     name: 'Muscara',      tier: 2, rarity: 'rare',      is_base_species: false, parent_a_id: 6,  parent_b_id: 2,  body_color: '#78b848', stem_color: '#486828', eye_color: '#203010', description: 'Tige musclée impossible à briser. Inspirée du bambou de montagne.' },
    { id: 21, slug: 'solanara',    name: 'Solanara',     tier: 2, rarity: 'rare',      is_base_species: false, parent_a_id: 18, parent_b_id: 10, body_color: '#e89040', stem_color: '#b05010', eye_color: '#602800', description: 'Parenté lointaine avec les solanacées. Baies lumineuses mais toxiques.' },
    { id: 22, slug: 'hostrelis',   name: 'Hostrelis',    tier: 2, rarity: 'epic',      is_base_species: false, parent_a_id: 7,  parent_b_id: 8,  body_color: '#c070e0', stem_color: '#803090', eye_color: '#400050', description: 'Feuilles veinées de lumière qui pulsent la nuit. Cousin obscur de l\'hosta.' },
    { id: 23, slug: 'aquamoss',    name: 'Aquamoss',     tier: 2, rarity: 'rare',      is_base_species: false, parent_a_id: 9,  parent_b_id: 1,  body_color: '#50c880', stem_color: '#208850', eye_color: '#084828', description: 'Tapis de mousse aquatique dense. Purifie l\'eau de son environnement.' },
    { id: 31, slug: 'nullherba',   name: 'Nullherba',    tier: 2, rarity: 'epic',      is_base_species: false, parent_a_id: 19, parent_b_id: 8,  body_color: '#909090', stem_color: '#606060', eye_color: '#303030', description: 'Ni vivante ni morte. Les botanistes ne s\'accordent pas sur sa classification.' },
    { id: 33, slug: 'mycelune',    name: 'Mycélune',     tier: 2, rarity: 'rare',      is_base_species: false, parent_a_id: 18, parent_b_id: 9,  body_color: '#b8d8a0', stem_color: '#6f8f58', eye_color: '#304830', description: 'Champignon-liane lunaire. Ses spores dessinent des anneaux pâles au pied du pot.' },

    // ── Tier 3 ───────────────────────────────────────────────────────────────
    { id: 15, slug: 'nebulosa',    name: 'Nebulosa',     tier: 3, rarity: 'legendary', is_base_species: false, parent_a_id: 11, parent_b_id: 12, body_color: '#9060f0', stem_color: '#5020c0', eye_color: '#200880', description: 'Aura nébuleuse multicolore. Extrêmement difficile à obtenir.' },
    { id: 16, slug: 'tempestia',   name: 'Tempestia',    tier: 3, rarity: 'legendary', is_base_species: false, parent_a_id: 14, parent_b_id: 13, body_color: '#6080f0', stem_color: '#3040c0', eye_color: '#101880', description: 'Maîtrise eau et feu. Tempête perpétuelle autour de sa tige.' },
    { id: 24, slug: 'drosalia',    name: 'Drosalia',     tier: 3, rarity: 'legendary', is_base_species: false, parent_a_id: 11, parent_b_id: 23, body_color: '#d060a0', stem_color: '#902070', eye_color: '#500040', description: 'Gouttelettes cristallines piègent les insectes. Cousine obscure du drosera.' },
    { id: 25, slug: 'heliorna',    name: 'Heliorna',     tier: 3, rarity: 'legendary', is_base_species: false, parent_a_id: 21, parent_b_id: 10, body_color: '#f0c020', stem_color: '#c08000', eye_color: '#705000', description: 'Suit la source de chaleur la plus proche. Évolution étrange du tournesol.' },
    { id: 26, slug: 'ferrosa',     name: 'Ferrosa',      tier: 3, rarity: 'legendary', is_base_species: false, parent_a_id: 20, parent_b_id: 14, body_color: '#90a8b8', stem_color: '#506878', eye_color: '#203040', description: 'Tiges dures comme de l\'acier glacé. Conduit l\'électricité par temps humide.' },
    { id: 27, slug: 'mandrova',    name: 'Mandrova',     tier: 3, rarity: 'legendary', is_base_species: false, parent_a_id: 22, parent_b_id: 12, body_color: '#802060', stem_color: '#500030', eye_color: '#280018', description: 'Cri silencieux, racines humanoïdes. Très peu de joueurs savent qu\'elle existe.' },

    // ── Tier 4 ───────────────────────────────────────────────────────────────
    { id: 17, slug: 'apex_obscura',  name: 'APEX OBSCURA',  tier: 4, rarity: 'mythic', is_base_species: false, parent_a_id: 15, parent_b_id: 16, body_color: '#f0d000', stem_color: '#c0a000', eye_color: '#806000', description: 'La plante ultime. Une seule peut exister sur le serveur à la fois.' },
    { id: 28, slug: 'phantasma',     name: 'Phantasma',     tier: 4, rarity: 'mythic', is_base_species: false, parent_a_id: 15, parent_b_id: 27, body_color: '#e0b0ff', stem_color: '#a060d0', eye_color: '#502888', description: 'Corps semi-transparent. Apparaît et disparaît selon l\'humidité ambiante.' },
    { id: 29, slug: 'aurorablis',    name: 'Aurorablis',    tier: 4, rarity: 'mythic', is_base_species: false, parent_a_id: 16, parent_b_id: 25, body_color: '#f0d880', stem_color: '#d0a030', eye_color: '#806010', description: 'Aurore boréale végétale. Produit une lumière visible à plusieurs kilomètres.' },
    { id: 30, slug: 'ferrobscura',   name: 'Ferrobscura',   tier: 4, rarity: 'mythic', is_base_species: false, parent_a_id: 26, parent_b_id: 24, body_color: '#608090', stem_color: '#304050', eye_color: '#101828', description: 'Armure de cristaux métalliques. Deuxième apex, chemin alternatif vers le sommet.' },
    { id: 32, slug: 'chronofolia',   name: 'Chronofolia',   tier: 4, rarity: 'mythic', is_base_species: false, parent_a_id: 15, parent_b_id: 26, body_color: '#d0e8b0', stem_color: '#90b860', eye_color: '#405030', description: 'Les anneaux de sa tige comptent les heures du serveur. Seuls les patients la voient.' },
  ];
}