// Copy to shared/config.js for local static testing.
// Production shared/config.js is generated by .github/workflows/deploy-ovh.yml.

export const SUPABASE_URL = 'https://your-project.supabase.co';
export const SUPABASE_ANON = 'your-public-anon-key';
