// Nitro app registry.
// Central list used by the hub, docs and Star dashboard widgets.

export const NITRO_APPS = [
  {
    id: 'star',
    name: 'Star Cockpit',
    url: '/star/',
    icon: '⬡',
    status: 'active',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/',
    description: 'Cockpit membre Nitro : crew, CIG, widgets, activité réseau et accès aux modules Star.',
    quickAccess: true,
    quickLabel: 'STAR',
    quickDesc: 'Cockpit membre',
    color: '--c-primary',
  },
  {
    id: 'star-aero',
    name: 'Star Aero Cockpit',
    url: '/star/aero.html',
    icon: '🫧',
    status: 'prototype',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/aero.html',
    description: 'Cockpit spatial Frutiger Aero : hublot océanique, HUD glossy, radar orbital et commandes Aqua Orbit.',
    quickAccess: true,
    quickLabel: 'AERO',
    quickDesc: 'Cockpit Frutiger',
    color: '--c-cyan',
  },
  {
    id: 'star-frutiger-globe',
    name: 'Aqua Globe',
    url: '/star/frutiger-globe/',
    icon: '🌐',
    status: 'prototype',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/frutiger-globe/',
    description: 'Variation Frutiger Aero centrée sur un globe aquatique, des bulles et une navigation lumineuse.',
    quickAccess: true,
    quickLabel: 'GLOBE',
    quickDesc: 'Frutiger Aqua',
    color: '--c-cyan',
  },
  {
    id: 'star-frutiger-biome',
    name: 'BioGlass Biome',
    url: '/star/frutiger-biome/',
    icon: '🌿',
    status: 'prototype',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/frutiger-biome/',
    description: 'Variation Frutiger Aero végétale : serre spatiale, feuilles glossy et bulles d’oxygène.',
    quickAccess: true,
    quickLabel: 'BIOME',
    quickDesc: 'Frutiger végétal',
    color: '--c-green',
  },
  {
    id: 'star-frutiger-dock',
    name: 'Aero Dock',
    url: '/star/frutiger-dock/',
    icon: '◈',
    status: 'prototype',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/frutiger-dock/',
    description: 'Launcher Frutiger Aero avec bulles d’applications, tuiles translucides et raccourcis lumineux.',
    quickAccess: true,
    quickLabel: 'DOCK',
    quickDesc: 'Launcher Frutiger',
    color: '--c-purple',
  },
  {
    id: 'nested-loops',
    name: 'Nested Loops',
    url: '/star/nested-loops/',
    icon: '◎',
    status: 'prototype',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/nested-loops/',
    description: 'Simulation cinétique inspirée de Chuck Hoberman / MoMath : boucles imbriquées, modes miroir, continu et axes de déploiement.',
    quickAccess: true,
    quickLabel: 'NESTED LOOPS',
    quickDesc: 'Simulation Hoberman',
    color: '--c-purple',
  },
  {
    id: 'star-jukebox-3d',
    name: 'Star Jukebox 3D',
    url: '/star/jukebox-3d/',
    icon: '🎚️',
    status: 'prototype',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/jukebox-3d/',
    description: 'Jukebox WebGL Star : platine 3D, vinyles stylisés, bibliothèque de pochettes et lecture locale.',
    quickAccess: true,
    quickLabel: 'JUKEBOX 3D',
    quickDesc: 'Vinyles · WebGL',
    color: '--c-green',
  },
  {
    id: 'sterenna-panel',
    name: 'Sterenna QG Panel',
    url: '/star/sterenna-panel/',
    icon: '◈',
    status: 'prototype',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/sterenna-panel/',
    description: 'Dashboard QG adapté au site statique Star : moniteurs locaux, fond 3D, hublot et console admin.',
    quickAccess: true,
    quickLabel: 'QG PANEL',
    quickDesc: 'Dashboard · admin',
    color: '--c-cyan',
  },
  {
    id: 'star-arcade',
    name: 'Star Arcade',
    url: '/arena/arcade-casino/',
    icon: '🎮',
    status: 'active',
    scope: 'nitro-app',
    auth: 'required',
    repo: 'sterenna-studio/skill-arena',
    deployPath: '~/nitro/arena/arcade-casino/',
    description: 'Arcade Star avec Whack-A-Mole, Crash, Slot Machine et Neon Racer.',
    quickAccess: false,
    hero: true,
    heroTitle: 'ARCADE',
    heroEyebrow: '// STAR · RÉSEAU',
    heroSub: 'WHACK-A-MOLE · CRASH · NEON RACER · SLOTS',
    heroBadge: '4 JEUX',
    quickLabel: 'ARCADE',
    quickDesc: 'Casino · mini-jeux',
    color: '--c-amber',
  },
  {
    id: 'botanica',
    name: 'Botanica Obscura',
    url: '/botanica/',
    icon: '🌿',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'required',
    repo: 'sterenna-studio/botanica-obscura',
    deployPath: '~/nitro/botanica/',
    description: 'Idle gacha botanique : mutations, pots, codex partagé, XP, jardin et découvertes serveur.',
    quickAccess: false,
    hero: true,
    heroTitle: 'BOTANICA OBSCURA',
    heroEyebrow: '// LAB · JARDIN',
    heroSub: 'IDLE GACHA · MUTATIONS · CODEX PARTAGÉ',
    heroBadge: 'ALPHA',
    quickLabel: 'BOTANICA',
    quickDesc: 'Jardin · gacha',
    color: '--c-green',
  },
  {
    id: 'clicker',
    name: 'Nitro Clicker',
    url: '/clicker/',
    icon: '✨',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'required',
    repo: 'sterenna-studio/nitro-clicker',
    deployPath: '~/nitro/clicker/',
    description: 'Clicker privé local-only : noyau cyber-biopunk, énergie, upgrades, jauges, tentacules, prestige.',
    quickAccess: false,
    hero: true,
    heroTitle: 'NITRO CLICKER',
    heroEyebrow: '// CORE · ÉNERGIE',
    heroSub: 'CLICKER · UPGRADES · PRESTIGE · BIOPUNK FX',
    heroBadge: 'LOCAL SAVE',
    quickLabel: 'CLICKER',
    quickDesc: 'Core · énergie',
    color: '--c-cyan',
  },
  {
    id: 'arena',
    name: 'Skill Arena',
    url: '/arena/',
    icon: '⚔️',
    status: 'active',
    scope: 'nitro-app',
    auth: 'optional',
    repo: 'sterenna-studio/skill-arena',
    deployPath: '~/nitro/arena/',
    description: 'Hub de mini-jeux de skill : réflexes, aim, frappe, perception, mémoire — solo et multijoueur en temps réel.',
    quickAccess: true,
    hero: true,
    heroTitle: 'SKILL ARENA',
    heroEyebrow: '// ARCADE · SKILL',
    heroSub: 'AIM · REACTION · TYPING · DUELS TEMPS RÉEL',
    heroBadge: 'MULTIJOUEUR',
    quickLabel: 'ARENA',
    quickDesc: 'Mini-jeux · duels',
    color: '--c-primary',
  },
  {
    id: 'titan-rocket-run',
    name: 'Titan Rocket Run',
    url: '/titan-rocket-run/',
    icon: '🚀',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'optional',
    repo: 'sterenna-studio/titan-rocket-run',
    deployPath: '~/nitro/titan-rocket-run/',
    description: 'Prototype HTML5 Canvas : Titan court, saute depuis la rampe et va le plus loin possible.',
    quickAccess: false,
    quickLabel: 'TITAN',
    quickDesc: 'Runner · score',
    color: '--c-amber',
  },
  {
    id: 'dedale',
    name: 'Dédale Temporel',
    url: '/dedale/',
    icon: '🚪',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'optional',
    repo: 'MutenRock/dedale-temporel',
    deployPath: '~/nitro/dedale/',
    description: "Couloir des portes temporelles — hub de l'escape game.",
    quickAccess: false,
    quickLabel: 'DÉDALE',
    quickDesc: 'Escape · portes',
    color: '--c-cyan',
  },
  {
    id: 'corebots',
    name: 'Corebots: Red Protocol',
    url: '/corebots/',
    icon: '🤖',
    status: 'beta',
    scope: 'internal',
    auth: 'optional',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/corebots/',
    description: 'Tower-defense WebAudio : protège le noyau, améliore gardiens/core/drones, survis aux vagues et aux boss. Score local, 100% généré (aucun asset audio externe).',
    quickAccess: false,
    quickLabel: 'COREBOTS',
    quickDesc: 'Tower-defense · local',
    color: '--c-red',
  },
  {
    id: 'tcg',
    name: 'Nitro TCG',
    url: '/TCG/',
    icon: '🃏',
    status: 'beta',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/TCG/',
    description: "Trading Card Game communautaire BZH Chronicles v4 : collection, boosters, boutique Chronicles, ouverture de packs.",
    quickAccess: false,
    hero: true,
    heroTitle: 'NITRO TCG',
    heroEyebrow: '// CARTES · CHRONICLES',
    heroSub: 'COLLECTION · BOOSTERS · BOUTIQUE CHRONICLES',
    heroBadge: 'BETA',
    quickLabel: 'TCG',
    quickDesc: 'Cartes · Chronicles',
    color: '--c-purple',
  },
  {
    id: 'bzh-universe',
    name: 'BZH Universe',
    url: '/bzh-universe/',
    icon: '🌌',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'optional',
    repo: 'sterenna-studio/bzh-universe',
    deployPath: '~/nitro/bzh-universe/',
    description: "Hub central de l'univers BZH Chronicles : lore, archives, manifest des projets et passerelles entre les jeux.",
    quickAccess: false,
    hero: true,
    heroTitle: 'BZH UNIVERSE',
    heroEyebrow: '// LORE · ARCHIVES',
    heroSub: 'UNIVERS · MANIFEST · PASSERELLES NITRO',
    heroBadge: 'ALPHA',
    quickLabel: 'BZH',
    quickDesc: 'Univers · lore',
    color: '--c-acid',
  },
  {
    id: 'jukebox',
    name: 'Jukebox',
    url: '/jukebox/',
    icon: '🎵',
    status: 'active',
    scope: 'internal',
    auth: 'optional',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/jukebox/',
    description: 'Lecteur musical communautaire et archives audio Dr.Spig / BZH Chronicles.',
    quickAccess: true,
    quickLabel: 'JUKEBOX',
    quickDesc: 'Musique · archives',
    color: '--c-green',
  },
  {
    id: 'pokegang',
    name: 'PokéGang',
    url: 'https://pokegang.sterenna.fr/',
    icon: '⚡',
    status: 'external-sync',
    scope: 'external',
    auth: 'optional-link',
    repo: 'sterenna-studio/pokegang-game',
    deployPath: '~/pokegang/',
    description: "Jeu autonome sur sous-domaine dédié, avec intégration Nitro progressive via CORS et liaison de compte.",
    quickAccess: false,
    hero: true,
    heroTitle: 'POKÉGANG',
    heroEyebrow: '// GANG · EXTERNE',
    heroSub: 'SOUS-DOMAINE · CAPTURE · RÉPUTATION · SYNC',
    heroBadge: 'LIVE',
    quickLabel: 'POKEGANG',
    quickDesc: 'Sous-domaine jeu',
    color: '--c-red',
  },
  {
    id: 'dedale',
    name: 'Dédale Temporel',
    url: '/dedale/',
    icon: '🚪',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'public',
    repo: 'sterenna-studio/dedale-temporel',
    deployPath: '~/nitro/dedale/',
    description: 'Escape game steampunk : couloir des portes temporelles, énigmes (SpectroCrypt, Imprimerie Médicale) et ambiance cuivre/vapeur.',
    quickAccess: false,
    hero: true,
    heroTitle: 'DÉDALE TEMPOREL',
    heroEyebrow: '// S.T.E.A.M. · COULOIR',
    heroSub: 'PORTES TEMPORELLES · ÉNIGMES · CUIVRE/VAPEUR',
    heroBadge: 'ALPHA',
    quickLabel: 'DÉDALE',
    quickDesc: 'Escape · énigmes',
    color: '--c-amber',
  },
];

export function getNitroApp(id) {
  return NITRO_APPS.find(app => app.id === id) ?? null;
}

export function getInternalNitroApps() {
  return NITRO_APPS.filter(app => app.scope !== 'external');
}

export function getQuickNitroApps() {
  return NITRO_APPS.filter(app => app.quickAccess);
}

export function getHeroNitroApps() {
  return NITRO_APPS.filter(app => app.hero);
}
