// Nitro app registry.
// Central list used by the hub, docs and Star dashboard widgets.

export const NITRO_APPS = [
  {
    id: 'star',
    name: 'Star Cockpit',
    url: '/star/',
    icon: '⬡',
    status: 'active',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/',
    description: 'Cockpit membre Nitro : crew, CIG, widgets, activité réseau et accès aux modules Star.',
    quickAccess: true,
    quickLabel: 'STAR',
    quickDesc: 'Cockpit membre',
    color: '--c-primary',
  },
  {
    id: 'star-arcade',
    name: 'Star Arcade',
    url: '/star/casino/',
    icon: '🎮',
    status: 'active',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/star/casino/',
    description: 'Arcade Star avec Whack-A-Mole, Crash, Slot Machine et Neon Racer.',
    quickAccess: false,
    hero: true,
    heroTitle: 'ARCADE',
    heroEyebrow: '// STAR · RÉSEAU',
    heroSub: 'WHACK-A-MOLE · CRASH · NEON RACER · SLOTS',
    heroBadge: '4 JEUX',
    quickLabel: 'ARCADE',
    quickDesc: 'Casino · mini-jeux',
    color: '--c-amber',
  },
  {
    id: 'botanica',
    name: 'Botanica Obscura',
    url: '/botanica-obscura/',
    icon: '🌿',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'required',
    repo: 'sterenna-studio/botanica-obscura',
    deployPath: '~/nitro/botanica-obscura/',
    description: 'Idle gacha botanique : mutations, pots, codex partagé, XP, jardin et découvertes serveur.',
    quickAccess: false,
    hero: true,
    heroTitle: 'BOTANICA OBSCURA',
    heroEyebrow: '// LAB · JARDIN',
    heroSub: 'IDLE GACHA · MUTATIONS · CODEX PARTAGÉ',
    heroBadge: 'ALPHA',
    quickLabel: 'BOTANICA',
    quickDesc: 'Jardin · gacha',
    color: '--c-green',
  },
  {
    id: 'clicker',
    name: 'Nitro Clicker',
    url: '/clicker/',
    icon: '✨',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'required',
    repo: 'sterenna-studio/nitro-clicker',
    deployPath: '~/nitro/clicker/',
    description: 'Clicker privé local-only : noyau cyber-biopunk, énergie, upgrades, jauges, tentacules, prestige.',
    quickAccess: false,
    hero: true,
    heroTitle: 'NITRO CLICKER',
    heroEyebrow: '// CORE · ÉNERGIE',
    heroSub: 'CLICKER · UPGRADES · PRESTIGE · BIOPUNK FX',
    heroBadge: 'LOCAL SAVE',
    quickLabel: 'CLICKER',
    quickDesc: 'Core · énergie',
    color: '--c-cyan',
  },
  {
    id: 'arena',
    name: 'Skill Arena',
    url: '/arena/',
    icon: '⚔️',
    status: 'active',
    scope: 'nitro-app',
    auth: 'optional',
    repo: 'sterenna-studio/skill-arena',
    deployPath: '~/nitro/arena/',
    description: 'Hub de mini-jeux de skill : réflexes, aim, frappe, perception, mémoire — solo et multijoueur en temps réel.',
    quickAccess: true,
    hero: true,
    heroTitle: 'SKILL ARENA',
    heroEyebrow: '// ARCADE · SKILL',
    heroSub: 'AIM · REACTION · TYPING · DUELS TEMPS RÉEL',
    heroBadge: 'MULTIJOUEUR',
    quickLabel: 'ARENA',
    quickDesc: 'Mini-jeux · duels',
    color: '--c-primary',
  },
  {
    id: 'titan-rocket-run',
    name: 'Titan Rocket Run',
    url: '/titan-rocket-run/',
    icon: '🚀',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'optional',
    repo: 'sterenna-studio/titan-rocket-run',
    deployPath: '~/nitro/titan-rocket-run/',
    description: 'Prototype HTML5 Canvas : Titan court, saute depuis la rampe et va le plus loin possible.',
    quickAccess: false,
    quickLabel: 'TITAN',
    quickDesc: 'Runner · score',
    color: '--c-amber',
  },
  {
    id: 'tcg',
    name: 'Nitro TCG',
    url: '/TCG/',
    icon: '🃏',
    status: 'alpha',
    scope: 'internal',
    auth: 'required',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/TCG/',
    description: "Trading Card Game communautaire lié à l'univers Star / BZH Chronicles.",
    quickAccess: true,
    quickLabel: 'TCG',
    quickDesc: 'Cartes · collection',
    color: '--c-purple',
  },
  {
    id: 'bzh-universe',
    name: 'BZH Universe',
    url: '/bzh-universe/',
    icon: '🌌',
    status: 'alpha',
    scope: 'nitro-app',
    auth: 'optional',
    repo: 'sterenna-studio/bzh-universe',
    deployPath: '~/nitro/bzh-universe/',
    description: "Hub central de l'univers BZH Chronicles : lore, archives, manifest des projets et passerelles entre les jeux.",
    quickAccess: true,
    quickLabel: 'BZH',
    quickDesc: 'Univers · lore',
    color: '--c-acid',
  },
  {
    id: 'jukebox',
    name: 'Jukebox',
    url: '/jukebox/',
    icon: '🎵',
    status: 'active',
    scope: 'internal',
    auth: 'optional',
    repo: 'sterenna-studio/gwen-ha-star-static',
    deployPath: '~/nitro/jukebox/',
    description: 'Lecteur musical communautaire et archives audio Dr.Spig / BZH Chronicles.',
    quickAccess: true,
    quickLabel: 'JUKEBOX',
    quickDesc: 'Musique · archives',
    color: '--c-green',
  },
  {
    id: 'pokegang',
    name: 'PokéGang',
    url: 'https://pokegang.sterenna.fr/',
    icon: '⚡',
    status: 'external-sync',
    scope: 'external',
    auth: 'optional-link',
    repo: 'sterenna-studio/pokegang-game',
    deployPath: '~/pokegang/',
    description: "Jeu autonome sur sous-domaine dédié, avec intégration Nitro progressive via CORS et liaison de compte.",
    quickAccess: true,
    quickLabel: 'POKEGANG',
    quickDesc: 'Sous-domaine jeu',
    color: '--c-red',
  },
];

export function getNitroApp(id) {
  return NITRO_APPS.find(app => app.id === id) ?? null;
}

export function getInternalNitroApps() {
  return NITRO_APPS.filter(app => app.scope !== 'external');
}

export function getQuickNitroApps() {
  return NITRO_APPS.filter(app => app.quickAccess);
}

export function getHeroNitroApps() {
  return NITRO_APPS.filter(app => app.hero);
}
